version: '3.8'

services:

  database:
    container_name: database
    build: database
    ports:
      - "3306:3306"
    networks:
      - jpetstore
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    container_name: app
    build: app
    ports:
      - 8080:8080
    networks:
      - jpetstore
    depends_on:
      - database



networks:
  jpetstore:
    name: jpet      

